### ISSUE TITLE
Navbar burger button don't working

### ISSUE THREAD

**Issue by ubaidisaev** [VizuaaLOG/BulmaJS-Docs#6]
Where I can see the source code of the site. I will gladly help.

Chrome 76.0.3809.100, (64 бит)

![error](https://user-images.githubusercontent.com/38039843/63642421-5813e080-c6c7-11e9-963a-76dee045d033.JPG)

**Comment by VizuaaLOG** [comment]
Hey @ubaid-dev,

Thank you for reporting this, looks to be an issue with the current dev build (which the docs use on some pages for testing purposes). I've created an issue over on the primary [BulmaJS repo](https://github.com/VizuaaLOG/BulmaJS).

**Comment by VizuaaLOG** [comment]
Thank you for reporting this. This has now been fixed in the BulmaJS core, and the documentation is now using the latest master build. Thanks again!
